In [81]:
from itertools import product
from itertools import combinations
from numpy import unique

In [82]:
# n=3
# q=2
# FF = GF(q)
# so = FF.cardinality()^n-1
# thm = (FF.cardinality()^n-1)^(n-1)
# G = GL(n, FF)
# M = MatrixSpace(FF,n,n)
# V = VectorSpace(FF,n)
# nq=gaussian_binomial(n,1,q=q)

In [83]:
#General structure/setting of GL(n,q)


#generate all hyperplanes of gl(n,q)
#output as a simple matrix
def get_hyperplanes(n,q): 
    FF = GF(q)
    H = []
    for i in range(n):
        h = matrix(FF,n-1,n)
        for j in range(n):
            if j<i:
                h[j,j] = 1
            if j>i:
                h[j-1,j] = 1
        if i >0:
            comblist = [p for p in product(GF(q), repeat=i)]
            num = len(comblist)
            for k in range(num):
                b = h
                v = comblist[k]
                for l in range(i):
                    b[l,i] = v[l]
                H.append(copy(b))
        else: H.append(h)
    return H

#generate all reflections
#input n,q and the determinant
def is_reflection(g):
    q=order(g.base_ring())
    n=(g.matrix()).nrows()
    G=GL(n,GF(q))
    M = g.matrix() - (G[0]^0).matrix()
    KM = M.kernel()
    return KM.dimension() == n-1


def get_refls(n,q,a): #find all reflections in a list
    R = []
    FF = GF(q)
    G = GL(n, FF)
    M = MatrixSpace(FF,n,n)
    for g in G:
        m = g.matrix() - (G[0]^0).matrix()
        KM = m.kernel()
        if KM.dimension() == n-1 and M(g).determinant() == a:
            R.append(g)
    return R

#gives the hyperplane the reflection element g fixes
def find_hyperplane(g):
    q=order(g.base_ring())
    n=(g.matrix()).nrows()
    G=GL(n,GF(q))
    M = g.matrix() - (G[0]^0).matrix()
    m = kernel(M)
    return m.matrix()



In [151]:
#Jucys-Murphy
#But this needs to change!

def JM(n,q,a):
    FF = GF(q)
    G = GL(n, FF)
    M = MatrixSpace(FF,n,n)
    m=matrix(n-1,n)
    for i in range(n-1):
        m[i,i]=1
    hyp = m
    ide = zero_vector(n)
    ide[-1] = 1
    JM_list = []
    for r in G:
        if is_reflection(r) and M(r).determinant() == a:
            if matrix(r)[-1]== ide and matrix(r).transpose()[-1] == ide:
                JM_list.append(r)
    return JM_list
    

In [121]:
R=get_refls(3,2,1)

In [136]:
R

[
[0 0 1]  [0 0 1]  [0 1 0]  [0 1 0]  [0 1 1]  [0 1 1]  [1 0 0]  [1 0 0]
[0 1 0]  [1 1 1]  [1 0 0]  [1 0 0]  [0 1 0]  [1 0 1]  [0 0 1]  [0 1 0]
[1 0 0], [1 0 0], [0 0 1], [1 1 1], [1 1 0], [0 0 1], [0 1 0], [0 1 1],

[1 0 0]  [1 0 0]  [1 0 0]  [1 0 0]  [1 0 0]  [1 0 0]  [1 0 0]  [1 0 1]
[0 1 0]  [0 1 0]  [0 1 1]  [1 0 1]  [1 1 0]  [1 1 0]  [1 1 1]  [0 1 0]
[1 0 1], [1 1 1], [0 0 1], [1 1 0], [0 0 1], [1 0 1], [0 0 1], [0 0 1],

[1 0 1]  [1 1 0]  [1 1 0]  [1 1 1]  [1 1 1]
[0 1 1]  [0 1 0]  [0 1 0]  [0 0 1]  [0 1 0]
[0 0 1], [0 0 1], [0 1 1], [0 1 0], [0 0 1]
]

In [155]:
#JM element of (n,q,det) = (3,3,1)
JM(3,3,1)

[
[0 1 0]  [0 2 0]  [1 0 0]  [1 0 0]  [1 1 0]  [1 2 0]  [2 1 0]  [2 2 0]
[2 2 0]  [1 2 0]  [1 1 0]  [2 1 0]  [0 1 0]  [0 1 0]  [2 0 0]  [1 0 0]
[0 0 1], [0 0 1], [0 0 1], [0 0 1], [0 0 1], [0 0 1], [0 0 1], [0 0 1]
]