In [1]:
from itertools import product
from itertools import combinations
from numpy import unique

In [2]:
# n=3
# q=2
# FF = GF(q)
# so = FF.cardinality()^n-1
# thm = (FF.cardinality()^n-1)^(n-1)
# G = GL(n, FF)
# M = MatrixSpace(FF,n,n)
# V = VectorSpace(FF,n)
# nq=gaussian_binomial(n,1,q=q)

In [3]:
#General structure/setting of GL(n,q)


#generate all hyperplanes of gl(n,q)
#output as a simple matrix
def get_hyperplanes(n,q): 
    FF = GF(q)
    H = []
    for i in range(n):
        h = matrix(FF,n-1,n)
        for j in range(n):
            if j<i:
                h[j,j] = 1
            if j>i:
                h[j-1,j] = 1
        if i >0:
            comblist = [p for p in product(GF(q), repeat=i)]
            num = len(comblist)
            for k in range(num):
                b = h
                v = comblist[k]
                for l in range(i):
                    b[l,i] = v[l]
                H.append(copy(b))
        else: H.append(h)
    return H

#generate all reflections
#input n,q and the determinant
def is_reflection(g):
    q=order(g.base_ring())
    n=(g.matrix()).nrows()
    G=GL(n,GF(q))
    M = g.matrix() - (G[0]^0).matrix()
    KM = M.kernel()
    return KM.dimension() == n-1


def get_refls(n,q,a): #find all reflections in a list
    R = []
    FF = GF(q)
    G = GL(n, FF)
    M = MatrixSpace(FF,n,n)
    for g in G:
        m = g.matrix() - (G[0]^0).matrix()
        KM = m.kernel()
        if KM.dimension() == n-1 and M(g).determinant() == a:
            R.append(g)
    return R

#gives the hyperplane the reflection element g fixes
def find_hyperplane(g):
    q=order(g.base_ring())
    n=(g.matrix()).nrows()
    G=GL(n,GF(q))
    M = g.matrix() - (G[0]^0).matrix()
    m = kernel(M)
    return m.matrix()



In [12]:
#Jucys-Murphy
#But this needs to change!

def JM(n,q,a):
    FF = GF(q)
    G = GL(n, FF)
    M = MatrixSpace(FF,n,n)
    m=matrix(n-1,n)
    for i in range(n-1):
        m[i,i]=1
    hyp = m
    ide = zero_vector(n)
    ide[-1] = 1
    JM_list = []
    for r in G:
        if is_reflection(r) and M(r).determinant() == a:
            if matrix(r)[-1]!= ide or matrix(r).transpose()[-1] != ide:
                JM_list.append(r)
    return JM_list

def JM_int(n,q,a):
    FF = GF(q)
    G = GL(n, FF)
    M = MatrixSpace(FF,n,n)
    m=matrix(n-1,n)
    for i in range(n-1):
        m[i,i]=1
    hyp = m
    ide = zero_vector(n)
    ide[-1] = 1
    JM_list = []
    for r in G:
        if is_reflection(r) and M(r).determinant() == a:
            if matrix(r)[-1]== ide and matrix(r).transpose()[-1] != ide:
                JM_list.append(r)
    return JM_list
    

In [13]:
get_refls(3,2,1)

[
[1 0 0]  [1 1 0]  [1 0 0]  [1 1 0]  [1 0 0]  [1 1 1]  [1 0 0]  [1 0 0]
[0 1 0]  [0 1 0]  [1 0 1]  [0 1 0]  [0 1 0]  [0 0 1]  [0 1 0]  [0 1 1]
[1 0 1], [0 1 1], [1 1 0], [0 0 1], [1 1 1], [0 1 0], [0 1 1], [0 0 1],

[0 0 1]  [1 0 1]  [0 1 0]  [0 1 0]  [0 0 1]  [1 0 0]  [1 0 0]  [1 1 1]
[1 1 1]  [0 1 0]  [1 0 0]  [1 0 0]  [0 1 0]  [0 0 1]  [1 1 1]  [0 1 0]
[1 0 0], [0 0 1], [1 1 1], [0 0 1], [1 0 0], [0 1 0], [0 0 1], [0 0 1],

[1 0 0]  [1 0 0]  [0 1 1]  [0 1 1]  [1 0 1]
[1 1 0]  [1 1 0]  [0 1 0]  [1 0 1]  [0 1 1]
[0 0 1], [1 0 1], [1 1 0], [0 0 1], [0 0 1]
]

In [14]:
JM(3,2,1)

[
[1 0 0]  [1 1 0]  [1 0 0]  [1 0 0]  [1 1 1]  [1 0 0]  [1 0 0]  [0 0 1]
[0 1 0]  [0 1 0]  [1 0 1]  [0 1 0]  [0 0 1]  [0 1 0]  [0 1 1]  [1 1 1]
[1 0 1], [0 1 1], [1 1 0], [1 1 1], [0 1 0], [0 1 1], [0 0 1], [1 0 0],

[1 0 1]  [0 1 0]  [0 0 1]  [1 0 0]  [1 0 0]  [1 1 1]  [1 0 0]  [0 1 1]
[0 1 0]  [1 0 0]  [0 1 0]  [0 0 1]  [1 1 1]  [0 1 0]  [1 1 0]  [0 1 0]
[0 0 1], [1 1 1], [1 0 0], [0 1 0], [0 0 1], [0 0 1], [1 0 1], [1 1 0],

[0 1 1]  [1 0 1]
[1 0 1]  [0 1 1]
[0 0 1], [0 0 1]
]

In [15]:
JM_int(3,2,1)

[
[1 0 0]  [1 0 1]  [1 0 0]  [1 1 1]  [0 1 1]  [1 0 1]
[0 1 1]  [0 1 0]  [1 1 1]  [0 1 0]  [1 0 1]  [0 1 1]
[0 0 1], [0 0 1], [0 0 1], [0 0 1], [0 0 1], [0 0 1]
]

**# Scott Andrews unipotent modules construction**

In [5]:
#testing out for n=2 q=2
#set up
n=4
q=2

In [6]:
FF = GF(q)
G = GL(n, FF)
M = MatrixSpace(FF,n,n)
V = VectorSpace(FF,n)

In [7]:
#build elementary vectors to extract basis from each element in G
#This is techinically overproducing because order matters and may be unnecessary. I'm still unsure about these ordered basis consturction

e_list=[]
for i in range(n):
    e = zero_vector(n)
    e[i] = 1
    e_list.append(e)
e_list

#the list of all ordered basis, where the first one is the standared ordered basis
ordered_basis=[]
for g in G.list():
    b=[]
    for e in e_list:
        b.append(g*e)
    ordered_basis.append(b)

standard = ordered_basis[0]

In [9]:
standard

[(1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1)]

In [8]:
#Choose your lambda
lam_list = Partitions(n).list()
lam = lam_list[1]
lam

[3, 1]

Building U(T) and P(T)

In [ ]:

#input: a partition, output:[cell, vector] 
#one is in just a simple list of list and one is in dictionary. Just learned about dictionary and playing around with it

def basis1(T):
    tab = []
    b = ordered_basis[0]
    cell = T.cells()
    for i in range(n):
        tab.append([cell[i],b[i]])
    return tab

def basis_dict(T):
    test = {}
    b = ordered_basis[0]
    cell = T.cells()
    for i in range(n):
        vec = tuple(b[i])
        test[vec] = cell[i]
    return test

#Now i have a newn code here, putting in an order on a set of basis and also building a column reading tableau

def basis(v):
    b = {}
    for i in range(n):
        b[f"v{i+1}"] = v[i]
    return b

def tab(lam):
    l = {}
    T = lam.initial_column_tableau()
    for i in range(n):
        t = T.cells_containing(i+1)
        l[f"v{i+1}"] = t[0]
    return l
    

In [ ]:
d=basis_dict(lam)
b= basis(standard) #but can choose a different set of basis here as well
T = tab(lam)
cell = lam.cells()

span_left=[]
for i in range(1,n+1):
    #vi= tuple(i)
    sp=[]
    for j in range(1,n+1):
        #vj= tuple(j)
        if T[f"v{j}"][1]<T[f"v{i}"][1]:
            sp.append(b[f"v{j}"])
    if sp == []:
        sp = [zero_vector(n)]

    Sp = span(sp,FF)
    span_left.append(Sp)

span_right=[]
for i in range(1,n+1):
    #vi= tuple(i)
    sp=[]
    for j in range(1,n+1):
        #vj= tuple(j)
        if T[f"v{j}"][1]>=T[f"v{i}"][1]:
            sp.append(b[f"v{j}"])
    if sp == []:
        sp = [zero_vector(n)]

    Sp = span(sp,FF)
    span_right.append(Sp)


#This takes a long time as well because we have to go through all g in G. 
# If we only care about the ones from the standard basis and can generate the rest from the standard U and T
# Or even understand it enough to know which ones to care about, then we can definitely make it faster

U=[]
for g in G:
    booelan_list=[]
    for i in range(1,n+1):
        #vi = ordered_basis[0][i]
        if g*b[f"v{i}"] - b[f"v{i}"]  in span_left[i-1]:
            booelan_list.append(True)
        else:
            booelan_list.append(False)
    if all(booelan_list):
        U.append(g)


P=[]
for g in G:
    booelan_list=[]
    for i in range(1,n+1):
        #vi = ordered_basis[0][i]
        if g*b[f"v{i}"] in span_right[i-1]:
            booelan_list.append(True)
        else:
            booelan_list.append(False)
    if all(booelan_list):
        P.append(g)


In [ ]:
U;
P;

In [431]:
#Building X(T)
#output given in (i,j)
X=[]
for i in range(1,n+1):
    for j in range(1,n+1):
        if T[f"v{i}"][0] == T[f"v{j}"][0] and T[f"v{i}"][1]<T[f"v{j}"][1]:
            X.append([i,j])
            break

In [432]:
X

[[1, 3], [3, 4]]

Building m_T and e_T

In [155]:
#JM element of (n,q,det) = (3,3,1)
JM(3,3,1)

[
[0 1 0]  [0 2 0]  [1 0 0]  [1 0 0]  [1 1 0]  [1 2 0]  [2 1 0]  [2 2 0]
[2 2 0]  [1 2 0]  [1 1 0]  [2 1 0]  [0 1 0]  [0 1 0]  [2 0 0]  [1 0 0]
[0 0 1], [0 0 1], [0 0 1], [0 0 1], [0 0 1], [0 0 1], [0 0 1], [0 0 1]
]

In [341]:
RSK([[0,0,2],[0,1,0],[1,1,1]])

[[[1, 2, 3], [2, 3], [3]], [[1, 1, 3], [2, 3], [3]]]

In [339]:
RSK()

ValueError: invalid input